config/routes.rb
Rails.application.routes.draw do
  get 'user/show'
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :attendances, only: []
  resources :events do
    resources :attendances, only: [:create, :destroy], controller: 'attendances'
  end
  resources :users, only: [:show] do
    resources :events, only: [:new, :create]
  end

  resources :attendances, only: [] do
    member do
      delete 'remove_attendee', to: 'attendances#remove_attendee'
    end
  end
  
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  # associations
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', dependent: :destroy
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user

  has_many :invitations, dependent: :destroy
  has_many :invitees, through: :invitations, source: :invitee

  #validation
  validates :private, inclusion: { in: [true, false] }

  # scopes
  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }
  scope :public_events, -> { where(private: false) }
  scope :private_events, -> { where(private: true) }
  
  def editable_by?(user)
    creator == user
  end

  def deletable_by?(user)
    creator == user
  end

  def invite(user)
    invitations.create(invitee: user)
  end

  def invited?(user)
    invitees.include?(user)
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :invitee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # associations
  has_many :events, dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  has_many :invitations, dependent: :destroy
  has_many :invitees, through: :invitations, source: :invitee

  def remove_attendance(event)
    attended_events.delete(event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:date, :name])
  end

  def authorize_creator!
    unless @event.editable_by?(current_user)
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end

  def authorize_invited_user!
    unless @event.invited?(current_user)
      redirect_to root_path, alert: "You are not invited to this event."
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  before_action :authenticate_user!

  def remove_attendee
    @event = Event.find(params[:id])
    if @event.attendees.exists?(current_user.id)
      @event.attendees.delete(current_user)
      redirect_to @event, notice: 'You have been removed from the attendee list.'
    else
      redirect_to @event, alert: 'You are not attending this event.'
    end
  end
  
  def create
    @event = Event.find(params[:event_id])
    current_user.attendances.create(event: @event)
    redirect_to @event, notice: "You are now attending this event."
  end

  def destroy
    @attendance = current_user.attendances.find(params[:id])
    @event = @attendance.event
    @attendance.destroy
    redirect_to @event, notice: "You are no longer attending this event."
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = current_user.events.find(params[:id])
  end
  
  def update
    @event = current_user.events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end
  
  def invite
    @event = current_user.events.find(params[:id])
    invited_user = User.find(params[:user_id])

    if @event.private?
      invitation = @event.invitations.build(invitee: invited_user)
      if invitation.save
        redirect_to @event, notice: 'Invitation sent successfully.'
      else
        redirect_to @event, alert: 'Failed to send invitation.'
      end
    else
      redirect_to @event, alert: 'This event is not private.'
    end
  end

  private
  
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :date, :creator_id, :private)
  end

  def authorize_user
    unless current_user == @event.creator
      redirect_to @event, alert: "You are not authorized to perform this action."
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = current_user
    if @user
      @events = @user.events
      @attended_events = @user.attended_events
    else
      flash[:alert] = "User not found"
      redirect_to root_path
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_form.html.erb
<h1>New Event</h1>
<%= form_with(model: @event, url: events_path, format: :html) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>

  <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= form_with(model: @event, url: event_path(@event), method: :patch, format: :html) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>

  <%= form.submit %>
<% end %>

app/views/events/index.html.erb
<nav>
  <%= link_to "Home", root_path %> |
  <%= link_to 'All Events', events_path %> | 
  <%= link_to "User's Event ", user_show_path(current_user) %> | 
  <%= link_to 'New Event', new_user_event_path(current_user) %>
</nav>

<h3>Past Events</h3>
<ul>
  <% @events.past.each do |event| %>
    <li><%= event.name %> - <%= event.date %></li>
  <% end %>
</ul>

<h3>Upcoming Events</h3>
<ul>
  <% @events.upcoming.each do |event| %>
    <li><%= event.name %> - <%= event.date %></li>
  <% end %>
</ul>

<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. 
    <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= form_with(model: @event, url: events_path, format: :html) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>

  <div class="field">
    <%= form.label :private %>
    <%= form.check_box :private %>
  </div>

  <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<h2>Details of the Event</h2>

<h3><%= @event.name %></h3>

<p><strong>Date:</strong> <%= @event.date %></p>

<% if @event.attendees.any? %>
  <h3>Attendees:</h3>
  <ul>
    <% @event.attendees.each do |attendee| %>
      <li><%= attendee.email %></li>
    <% end %>
  </ul>
<% else %>
  <p>No attendees yet.</p>
<% end %>

<% if current_user == @event.creator %>
  <h3>Invitations:</h3>
  <% @event.invitees.each do |invitee| %>
    <p><%= invitee.email %></p>
  <% end %>
<% elsif @event.private? %>
  <p>This event is private.</p>
<% end %>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/user/show.html.erb
<h2>List of user's Attended Events</h2>
<% if @attended_events.any? %>
  <% @attended_events.each do |event| %>
    <h2><%= event.name %></h2>

    <% if event.attendees.any? %>
      <h3>Attendees:</h3>
      <ul>
        <% event.attendees.each do |attendee| %>
          <li><%= attendee.email %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No attendees found for this event.</p>
    <% end %>

    <%= link_to 'Edit', edit_event_path(event) %> |
  <% end %>
<% else %>
  <p>No events found.</p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>